ktor:
  application:
    modules:
      - com.gnomeshift.ApplicationKt.module
  deployment:
    port: 8080

db:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/kotlin-basics"
  user: ""
  password: ""

jwt:
  privateKeyPath: "./ktor/src/main/resources/private_key.pem"
  publicKeyPath: "./ktor/src/main/resources/public_key.pem"
  audience: "ktor-app"
  issuer: "ktor-app-issuer"
  realm: "ktor-app-realm"
  tokenExpirationMinutes: 1440