ktor:
  application:
    modules:
      - com.gnomeshift.ApplicationKt.module
  deployment:
    port: 8080

db:
  driver: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/kotlin-basics"
  user: ""
  password: ""